### ISSUE TITLE
Version of Ruby we are using.   

### ISSUE THREAD

**Issue by MarkJRigdon** [MarkJRigdon/dealership#1]
@jameslayman 
I was using Ruby 2.3.3 to code the previous stuff in class.   
Obvisouly we are using 2.5.1 for rails so let's make our code for this project in ruby 2.5.1.
That means I'll have to probably change my .spec files but no biggy. 
Can you confirm you are on 2.5.1 for this as well :)

**Comment by jameslayman** [comment]
@MarkJRigdon I am indeed using 2.5.1 so we can close this out.
